// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ListMcpServerToolsResponse {
    /** MCP `tools/list` entries, typed to the MCP Tool shape. */
    data: TrueForge.McpTool[];
}
