// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

/**
 * A single MCP `tools/list` entry.
 */
export interface McpTool {
    /** MCP-designated metadata, passed through verbatim. */
    meta?: Record<string, unknown>;
    annotations?: TrueForge.McpToolAnnotations;
    /** Human-readable description of what the tool does. */
    description?: string;
    execution?: TrueForge.McpToolExecution;
    /** Sized icons for the tool. */
    icons?: TrueForge.McpToolIcon[];
    inputSchema: TrueForge.McpToolJsonSchema;
    /** Programmatic identifier of the tool. */
    name: string;
    outputSchema?: TrueForge.McpToolJsonSchema;
    /** TrueForge hint: eagerly load this tool for the model. */
    preload?: boolean;
    /** Human-readable display title. */
    title?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
