// This file was auto-generated by Fern from our API Definition.

/**
 * A sized icon for a tool.
 */
export interface McpToolIcon {
    /** MIME type override, e.g. "image/png". */
    mimeType?: string;
    /** URI of the icon resource (HTTP(S) or data: URI). */
    src: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
