// This file was auto-generated by Fern from our API Definition.

/**
 * A JSON Schema object constraining a tool parameter or result.
 */
export interface McpToolJsonSchema {
    /** JSON Schema dialect identifier, e.g. "https://json-schema.org/draft/2020-12/schema". */
    schema?: string;
    /** Named property schemas. */
    properties?: Record<string, unknown>;
    /** Property names that must be present. */
    required?: string[];
    /** MCP tool schemas are objects at the root. */
    type: "object";
    /** Accepts any additional properties */
    [key: string]: any;
}
