// This file was auto-generated by Fern from our API Definition.

/** Whether the tool supports task-augmented (long-running) execution. */
export const McpToolExecutionTaskSupport = {
    Forbidden: "forbidden",
    Optional: "optional",
    Required: "required",
} as const;
export type McpToolExecutionTaskSupport =
    (typeof McpToolExecutionTaskSupport)[keyof typeof McpToolExecutionTaskSupport];
