// This file was auto-generated by Fern from our API Definition.

/**
 * Optional behavior hints.
 */
export interface McpToolAnnotations {
    /** If true, the tool may perform destructive updates. */
    destructiveHint?: boolean;
    /** If true, repeating identical calls has no additional effect. */
    idempotentHint?: boolean;
    /** If true, the tool may interact with an open world of external entities. */
    openWorldHint?: boolean;
    /** If true, the tool does not modify its environment. */
    readOnlyHint?: boolean;
    /** Human-readable title for the tool. */
    title?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
