// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpToolAnnotations: core.serialization.ObjectSchema<
    serializers.McpToolAnnotations.Raw,
    TrueForge.McpToolAnnotations
> = core.serialization
    .object({
        destructiveHint: core.serialization.boolean().optional(),
        idempotentHint: core.serialization.boolean().optional(),
        openWorldHint: core.serialization.boolean().optional(),
        readOnlyHint: core.serialization.boolean().optional(),
        title: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace McpToolAnnotations {
    export interface Raw {
        destructiveHint?: boolean | null;
        idempotentHint?: boolean | null;
        openWorldHint?: boolean | null;
        readOnlyHint?: boolean | null;
        title?: string | null;
        [key: string]: any;
    }
}
