// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpToolExecutionTaskSupport } from "./McpToolExecutionTaskSupport.js";

export const McpToolExecution: core.serialization.ObjectSchema<
    serializers.McpToolExecution.Raw,
    TrueForge.McpToolExecution
> = core.serialization
    .object({
        taskSupport: McpToolExecutionTaskSupport.optional(),
    })
    .passthrough();

export declare namespace McpToolExecution {
    export interface Raw {
        taskSupport?: McpToolExecutionTaskSupport.Raw | null;
        [key: string]: any;
    }
}
