// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpToolAnnotations } from "./McpToolAnnotations.js";
import { McpToolExecution } from "./McpToolExecution.js";
import { McpToolIcon } from "./McpToolIcon.js";
import { McpToolJsonSchema } from "./McpToolJsonSchema.js";

export const McpTool: core.serialization.ObjectSchema<serializers.McpTool.Raw, TrueForge.McpTool> = core.serialization
    .object({
        meta: core.serialization.property(
            "_meta",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        ),
        annotations: McpToolAnnotations.optional(),
        description: core.serialization.string().optional(),
        execution: McpToolExecution.optional(),
        icons: core.serialization.list(McpToolIcon).optional(),
        inputSchema: McpToolJsonSchema,
        name: core.serialization.string(),
        outputSchema: McpToolJsonSchema.optional(),
        preload: core.serialization.boolean().optional(),
        title: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace McpTool {
    export interface Raw {
        _meta?: Record<string, unknown> | null;
        annotations?: McpToolAnnotations.Raw | null;
        description?: string | null;
        execution?: McpToolExecution.Raw | null;
        icons?: McpToolIcon.Raw[] | null;
        inputSchema: McpToolJsonSchema.Raw;
        name: string;
        outputSchema?: McpToolJsonSchema.Raw | null;
        preload?: boolean | null;
        title?: string | null;
        [key: string]: any;
    }
}
