// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpToolIcon: core.serialization.ObjectSchema<serializers.McpToolIcon.Raw, TrueForge.McpToolIcon> =
    core.serialization
        .object({
            mimeType: core.serialization.string().optional(),
            src: core.serialization.string(),
        })
        .passthrough();

export declare namespace McpToolIcon {
    export interface Raw {
        mimeType?: string | null;
        src: string;
        [key: string]: any;
    }
}
